//go:build ignore

// gen.go はsandbox.protoのSHA-256を定数にしたsha.goを書く。`go generate`から走る。
// MASUDA_SANDBOX_DIRでmasuda-sandboxのチェックアウトを指せる（既定はリポジトリの隣）。
// CIはワークスペースの外にcheckoutできないので、場所を渡せるようにしている。
package main

import (
	"crypto/sha256"
	"fmt"
	"os"
	"path/filepath"
)

func main() {
	dir := os.Getenv("MASUDA_SANDBOX_DIR")
	if dir == "" {
		dir = filepath.Join("..", "..", "..", "masuda-sandbox")
	}
	proto := filepath.Join(dir, "proto", "masuda", "sandbox", "v1", "sandbox.proto")
	b, err := os.ReadFile(proto)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sandboxcontract: %v（masuda-sandboxを隣にチェックアウトするか、MASUDA_SANDBOX_DIRで場所を指定する）\n", err)
		os.Exit(1)
	}
	out := fmt.Sprintf(`// Code generated by gen.go from masuda-sandbox's proto/masuda/sandbox/v1/sandbox.proto. DO NOT EDIT.

package sandboxcontract

// SHA256 はmasudaのsandboxクライアント（gen/masuda/sandbox/v1）の生成元sandbox.protoの
// SHA-256（16進小文字）。GetServerInfoのcontract_sha256と同じ計算。
const SHA256 = %q
`, fmt.Sprintf("%x", sha256.Sum256(b)))
	if err := os.WriteFile("sha.go", []byte(out), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
