// Code generated by gen.go from masuda-sandbox's proto/masuda/sandbox/v1/sandbox.proto. DO NOT EDIT.

package sandboxcontract

// SHA256 はmasudaのsandboxクライアント（gen/masuda/sandbox/v1）の生成元sandbox.protoの
// SHA-256（16進小文字）。GetServerInfoのcontract_sha256と同じ計算。
const SHA256 = "495d811ea8588170ea8e69a5100b655a9177873df250236a744717b9c77627fd"
